name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.14'

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Test
      run: go test -count=1 -timeout 10s ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.29
